# Generated by Django 5.0.7 on 2024-08-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_bloom', '0003_service_alter_story_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='outline',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
    ]
