# Generated by Django 5.0.7 on 2024-09-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_bloom', '0008_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='advance_amt',
            field=models.IntegerField(default=123, max_length=30),
            preserve_default=False,
        ),
    ]
